# Generated by Django 5.0.6 on 2025-10-09 13:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['station_id'], name='ciclovias_s_station_e760a4_idx'), models.Index(fields=['name'], name='ciclovias_s_name_6484b3_idx')],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_id', models.CharField(max_length=255, unique=True)),
                ('duration_seconds', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('initial_station_name', models.CharField(max_length=255)),
                ('final_station_name', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('birth_year', models.CharField(blank=True, max_length=10)),
                ('initial_station_latitude', models.FloatField(blank=True, null=True)),
                ('initial_station_longitude', models.FloatField(blank=True, null=True)),
                ('final_station_latitude', models.FloatField(blank=True, null=True)),
                ('final_station_longitude', models.FloatField(blank=True, null=True)),
                ('start_day', models.IntegerField(blank=True, null=True)),
                ('start_hour', models.IntegerField(blank=True, null=True)),
                ('end_day', models.IntegerField(blank=True, null=True)),
                ('end_hour', models.IntegerField(blank=True, null=True)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('final_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arriving_trips', to='ciclovias.station')),
                ('initial_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departing_trips', to='ciclovias.station')),
            ],
            options={
                'indexes': [models.Index(fields=['start_time'], name='ciclovias_t_start_t_4e30fd_idx'), models.Index(fields=['end_time'], name='ciclovias_t_end_tim_4c762f_idx'), models.Index(fields=['start_day'], name='ciclovias_t_start_d_957895_idx'), models.Index(fields=['start_hour'], name='ciclovias_t_start_h_47765c_idx'), models.Index(fields=['month'], name='ciclovias_t_month_19b1df_idx'), models.Index(fields=['initial_station'], name='ciclovias_t_initial_bc8607_idx'), models.Index(fields=['final_station'], name='ciclovias_t_final_s_56e802_idx'), models.Index(fields=['trip_id'], name='ciclovias_t_trip_id_52f5e7_idx')],
            },
        ),
    ]
